import type { AppOrder, Delivery } from "@/types/app";

const defaultOrderValues = {
  company_id: "mock-company-id",
  user_id: "user-123",
  client_id: "client-abc",
  client_email: "test@test.com",
  client_phone: "555-1234",
  event_time: "18:00:00",
  venue_lat: -26.107567,
  venue_lng: 28.056702,
  subtotal: 37500,
  tax: 1200,
  total: 38700,
  deposit_amount: 19350,
  deposit_paid: true,
  deposit_paid_at: new Date(Date.now() - 86400000 * 10).toISOString(),
  balance_amount: 19350,
  balance_due_date: new Date(Date.now() + 86400000 * 5).toISOString(),
  balance_paid: false,
  balance_paid_at: null,
  payment_status: "partial" as "pending" | "partial" | "paid" | "refunded",
  delivery_status: "in_transit" as "pending" | "in_transit" | "delivered" | "completed",
  internal_notes: "Client has a nut allergy. Ensure no cross-contamination.",
  special_instructions: "Please set up the buffet by the main stage.",
  assigned_chef_id: "chef-a",
  assigned_driver_id: "driver-b",
  updated_at: new Date().toISOString(),
  region_id: "gauteng-jhb-north",
  last_change_allowed_date: new Date(Date.now() + 86400000 * 2).toISOString(),
  final_guest_count: 150,
  final_order_confirmed_at: new Date(Date.now() - 86400000 * 3).toISOString(),
  payment_reference: "PAY-123",
  payment_gateway: "PayFast",
  delivery_time: null,
  amount_paid: 19350,
  requires_waiter: false,
  collection_time: null,
  pickup_time: null,
  delivery_total_fee: 0,
  currency: 'ZAR',
  delivery_distance_km: null,
  delivery_duration_minutes: null,
  delivery_rate_per_km: null,
  delivery_route_optimized: false,
  equipment_return_method: 'later_collection',
  waiter_duration_hours: null,
  waiter_hourly_rate: null,
  waiter_service_required: false,
  waiter_total_fee: null,
  whatsapp_notifications_sent: [],
  xero_invoice_id: null,
  xero_synced_at: null,
  driver_id: null,
};

export const mockOrders: AppOrder[] = [
  {
    id: "ord-mock-1",
    ...defaultOrderValues,
    user_id: "user-123",
    company_id: "comp-456",
    quote_id: "quote-789",
    client_name: "John Doe",
    client_email: "john.doe@example.com",
    event_date: "2025-11-15",
    venue_address: "123 Main St, Anytown",
    guest_count: 50,
    total: 2500,
    status: "confirmed",
    order_number: "ORD-001",
    created_at: "2025-10-10T10:00:00Z",
    menu_items: [
      { id: "item-1", name: "Mini Quiches", quantity: 100, category: "appetizer" },
      { id: "item-2", name: "Chicken Skewers", quantity: 50, category: "main" },
    ],
    equipment_items: [
        { id: 'equip-1', name: 'Chafing Dish', quantity: 5, category: 'chafing' },
    ],
    kitchen_instructions: "Please ensure all chicken is well-done. One guest has a nut allergy.",
  },
  {
    id: "ord-mock-2",
    ...defaultOrderValues,
    quote_id: "Q-001",
    order_number: "ORD-001",
    client_name: "Sarah Johnson",
    event_date: new Date().toISOString().split("T")[0],
    venue_address: "Grand Palace Hotel, Ballroom A",
    guest_count: 150,
    menu_items: [
      { id: "m1", name: "Braai Platter", category: "main", pricePerPerson: 250, quantity: 150 },
    ],
    equipment_items: [
      { id: "eq1", name: "Dinner Plates", category: "crockery", quantity: 150 },
      { id: "eq2", name: "Wine Glasses", category: "crockery", quantity: 150 },
    ],
    status: "in_transit",
    created_at: new Date(Date.now() - 86400000 * 12).toISOString(),
    driverName: "John Doe",
    total: 38700,
    kitchen_instructions: "Prepare 2 hours before event. Marinate meat 24h in advance.",
    assigned_driver_id: "driver-b",
    driver_id: "driver-b", // Added for consistency
  },
  {
    id: "ord-mock-3",
    ...defaultOrderValues,
    quote_id: "Q-002",
    order_number: "ORD-002",
    client_name: "Mike Williams",
    client_email: "mike.w@example.com",
    client_phone: "555-5678",
    event_date: new Date(Date.now() + 86400000 * 7).toISOString().split("T")[0],
    event_time: "19:30:00",
    venue_address: "Beach Club Venue, Cape Town",
    venue_lat: -33.924870,
    venue_lng: 18.424055,
    guest_count: 80,
    menu_items: [
      { id: "m2", name: "Seafood Buffet", category: "main", pricePerPerson: 350, quantity: 80 },
    ],
    equipment_items: [],
    subtotal: 28000,
    tax: 4200,
    total: 32200,
    deposit_amount: 16100,
    deposit_paid_at: new Date(Date.now() - 86400000 * 5).toISOString(),
    balance_amount: 16100,
    balance_due_date: new Date(Date.now() + 86400000 * 1).toISOString(),
    status: "confirmed",
    delivery_status: "pending",
    internal_notes: "VIP client. Ensure everything is perfect.",
    special_instructions: "Serve oysters first.",
    created_at: new Date(Date.now() - 86400000 * 6).toISOString(),
    updated_at: new Date(Date.now() - 86400000).toISOString(),
    region_id: "western-cape-cpt",
    last_change_allowed_date: new Date(Date.now() + 86400000 * 3).toISOString(),
    final_guest_count: 80,
    final_order_confirmed_at: null,
    payment_reference: "PAY-456",
    amount_paid: 16100,
    requires_waiter: true,
    kitchen_instructions: null,
    assigned_driver_id: null,
    driver_id: null, // Added for consistency
  },
  {
    id: "ord-mock-4",
    ...defaultOrderValues,
    quote_id: "Q-003",
    order_number: "ORD-003",
    client_name: "Emily Brown",
    client_email: "emily.b@example.com",
    client_phone: "555-8765",
    event_date: new Date(Date.now() - 86400000 * 2).toISOString().split("T")[0],
    event_time: "13:00:00",
    venue_address: "Durban Exhibition Centre",
    venue_lat: -29.858680,
    venue_lng: 31.021840,
    guest_count: 300,
    menu_items: [{ id: "m3", name: "Corporate Lunch", category: "main", pricePerPerson: 180, quantity: 300 }],
    equipment_items: [],
    subtotal: 54000,
    tax: 8100,
    total: 62100,
    deposit_amount: 62100,
    deposit_paid: true,
    deposit_paid_at: new Date(Date.now() - 86400000 * 20).toISOString(),
    balance_amount: 0,
    balance_paid: true,
    balance_paid_at: new Date(Date.now() - 86400000 * 10).toISOString(),
    status: "completed",
    payment_status: "paid",
    delivery_status: "completed",
    internal_notes: "",
    special_instructions: "",
    assigned_chef_id: "chef-b",
    created_at: new Date(Date.now() - 86400000 * 22).toISOString(),
    updated_at: new Date(Date.now() - 86400000 * 2).toISOString(),
    region_id: "kzn-durban",
    last_change_allowed_date: new Date(Date.now() - 86400000 * 15).toISOString(),
    final_guest_count: 300,
    final_order_confirmed_at: new Date(Date.now() - 86400000 * 14).toISOString(),
    payment_reference: "PAY-789",
    payment_gateway: "EFT",
    delivery_time: new Date(Date.now() - 86400000 * 2).toISOString(),
    amount_paid: 62100,
    requires_waiter: false,
    kitchen_instructions: null,
    assigned_driver_id: "driver-c",
    driver_id: "driver-c", // Added for consistency
  },
];

export const mockDeliveries: Delivery[] = [
  {
    id: "DEL-001",
    orderId: "ORD-001",
    driverId: "driver-b",
    driverName: "John Doe",
    pickupTime: new Date(Date.now() - 3600000).toISOString(),
    deliveryTime: new Date(Date.now() + 3600000).toISOString(),
    location: "Grand Palace Hotel, Ballroom A",
    status: "in_transit",
  },
  {
    id: "DEL-002",
    orderId: "ORD-003",
    driverId: "driver-c",
    driverName: "Jane Smith",
    pickupTime: new Date(Date.now() - 86400000 * 2 - 3600000).toISOString(),
    deliveryTime: new Date(Date.now() - 86400000 * 2).toISOString(),
    location: "Durban Exhibition Centre",
    status: "completed",
  },
];

export const fullMockOrders: AppOrder[] = [
    {
      id: 'f-ord-1',
      ...defaultOrderValues,
      quote_id: 'Q-101',
      client_name: 'TechCorp Inc.',
      event_date: new Date(Date.now() + 86400000 * 3).toISOString(),
      venue_address: '123 Main St, Anytown',
      guest_count: 100,
      status: 'confirmed',
      total: 15000,
      order_number: "ORD-101",
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      kitchen_instructions: null,
      menu_items: [],
      equipment_items: [],
      driver_id: null,
    },
    {
      id: 'f-ord-2',
      ...defaultOrderValues,
      quote_id: 'Q-102',
      client_name: 'Innovate LLC',
      event_date: new Date(Date.now() + 86400000 * 5).toISOString(),
      venue_address: '456 Oak Ave, Somecity',
      guest_count: 50,
      status: 'preparing',
      total: 7500,
      order_number: "ORD-102",
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      kitchen_instructions: null,
      menu_items: [],
      equipment_items: [],
      driver_id: null,
    },
    {
      id: 'f-ord-3',
      ...defaultOrderValues,
      quote_id: 'Q-103',
      client_name: 'Solutions Ltd.',
      event_date: new Date(Date.now() + 86400000 * 10).toISOString(),
      venue_address: '789 Pine Rd, Otherplace',
      guest_count: 200,
      status: 'confirmed',
      total: 30000,
      order_number: "ORD-103",
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      kitchen_instructions: null,
      menu_items: [],
      equipment_items: [],
      driver_id: null,
    },
    {
      id: 'f-ord-4',
      ...defaultOrderValues,
      quote_id: 'Q-104',
      client_name: 'Future Systems',
      event_date: new Date(Date.now() + 86400000 * 1).toISOString(),
      venue_address: '101 Future Way, Tomorrowland',
      guest_count: 120,
      status: 'preparing',
      total: 18000,
      order_number: "ORD-104",
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      kitchen_instructions: null,
      menu_items: [],
      equipment_items: [],
      driver_id: null,
    },
    {
      id: 'f-ord-5',
      ...defaultOrderValues,
      quote_id: 'Q-105',
      client_name: 'Global Ventures',
      event_date: new Date(Date.now() + 86400000 * 12).toISOString(),
      venue_address: '202 Global Rd, World City',
      guest_count: 250,
      status: 'confirmed',
      total: 37500,
      order_number: "ORD-105",
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      kitchen_instructions: null,
      menu_items: [],
      equipment_items: [],
      driver_id: null,
    },
    {
      id: 'f-ord-6',
      ...defaultOrderValues,
      quote_id: 'Q-106',
      client_name: 'Data Dynamics',
      event_date: new Date(Date.now() + 86400000 * 20).toISOString(),
      venue_address: '303 Data Dr, Informationville',
      guest_count: 80,
      status: 'confirmed',
      total: 12000,
      order_number: "ORD-106",
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      kitchen_instructions: null,
      menu_items: [],
      equipment_items: [],
      driver_id: null,
    },
    {
      id: 'f-ord-7',
      ...defaultOrderValues,
      quote_id: 'Q-107',
      client_name: 'Creative Minds',
      event_date: new Date(Date.now() + 86400000 * 2).toISOString(),
      venue_address: '404 Art St, Ideatown',
      guest_count: 150,
      status: 'preparing',
      total: 22500,
      order_number: "ORD-107",
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      kitchen_instructions: null,
      menu_items: [],
      equipment_items: [],
      driver_id: null,
    },
];
