"use strict";(()=>{var e={};e.id=95932,e.ids=[78416,95932],e.modules={26373:e=>{e.exports=import("resend")},26780:(e,t,n)=>{n.a(e,async(e,r)=>{try{n.r(t),n.d(t,{config:()=>u,default:()=>c,routeModule:()=>d});var o=n(33480),i=n(8667),a=n(86435),s=n(28707),l=e([s]);s=(l.then?(await l)():l)[0];let c=(0,a.M)(s,"default"),u=(0,a.M)(s,"config"),d=new o.PagesAPIRouteModule({definition:{kind:i.A.PAGES_API,page:"/api/contact-form",pathname:"/api/contact-form",bundlePath:"",filename:""},userland:s});r()}catch(e){r(e)}})},28707:(e,t,n)=>{n.a(e,async(e,r)=>{try{n.r(t),n.d(t,{default:()=>m});var o=n(73217),i=n(26373),a=n(96153),s=n(90704),l=e([i]);i=(l.then?(await l)():l)[0];let d=process.env.PLATFORM_SUPPORT_INBOX||"support@cateringms.com",p=process.env.PLATFORM_FROM_EMAIL||"noreply@send.cateringms.com";async function c(e,t){if("POST"!==e.method)return t.status(405).json({error:"Method not allowed"});try{let n=e.body||{};if(n.website&&n.website.length>0)return t.status(200).json({ok:!0});let r=String(n.name||"").trim(),o=String(n.email||"").trim(),a=String(n.message||"").trim();if(!r||!o||!a)return t.status(400).json({error:"Name, email and message are required."});if(r.length>200||o.length>200||a.length>5e3)return t.status(413).json({error:"Submission too large."});if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(o))return t.status(400).json({error:"Email looks invalid."});let l=`[contact form] ${n.subject||"general"} - ${r}`,c=`
<p><strong>From:</strong> ${u(r)} &lt;${u(o)}&gt;</p>
${n.phone?`<p><strong>Phone:</strong> ${u(n.phone)}</p>`:""}
${n.company?`<p><strong>Company:</strong> ${u(n.company)}</p>`:""}
<p><strong>Subject:</strong> ${u(n.subject||"general")}</p>
<hr/>
<pre style="white-space: pre-wrap; font-family: inherit;">${u(a)}</pre>
${(0,s.e)("")}
`,m=process.env.RESEND_API_KEY;if(!m)return console.warn("[contact-form] RESEND_API_KEY missing, skipping send"),t.status(200).json({ok:!0,simulated:!0});let g=new i.Resend(m);return await g.emails.send({from:p,to:d,replyTo:o,subject:l,html:c}),t.status(200).json({ok:!0})}catch(e){return console.error("[contact-form] crashed:",e),t.status(500).json({error:(0,o._)(e)||"Could not send"})}}function u(e){return e.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#39;")}let m=(0,a.k)(c);r()}catch(e){r(e)}})},29021:e=>{e.exports=require("fs")},33873:e=>{e.exports=require("path")},75600:e=>{e.exports=require("next/dist/compiled/next-server/pages-api.runtime.prod.js")},78416:(e,t,n)=>{function r(e){let t=String(e||"").trim();return t?(/^https?:\/\//i.test(t)?t:`https://${t}`).replace(/\/+$/,""):""}function o(e,t){let n=r(process.env.NEXT_PUBLIC_APP_URL)||r(t)||r(process.env.NEXT_PUBLIC_SITE_URL)||"https://cateringms.com";return`${n}${function(e){let t=String(e||"").trim().replace(/^\/+|\/+$/g,"");return t?`/terms/${encodeURIComponent(t)}`:"/terms"}(e)}`}function i(e){return(("string"==typeof e?e.trim():"")||"CONFIDENTIALITY NOTICE: This email and any attachments are intended solely for the named recipient and may contain confidential, privileged, or personal information. If you received it in error, please notify the sender immediately, delete it, and do not copy, disclose, distribute, or rely on its contents.").slice(0,4e3)}n.d(t,{eF:()=>o,t$:()=>i})},90704:(e,t,n)=>{n.d(t,{e:()=>l,iZ:()=>c});var r=n(78416);let o=new Map;function i(e){return e.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#39;")}async function a(e,t){let n=o.get(e);if(n&&Date.now()-n.fetchedAt<3e5)return n.row;let r={slug:null,confidentiality_notice:null};try{let{data:n,error:o}=await t.from("companies").select("slug, confidentiality_notice").eq("id",e).maybeSingle();if(!o&&n)r={slug:n.slug||null,confidentiality_notice:n.confidentiality_notice||null};else if(o&&(o?.code==="42703"||/confidentiality_notice.*does not exist/i.test(String(o?.message||"")))){let n=await t.from("companies").select("slug").eq("id",e).maybeSingle();!n.error&&n.data&&(r.slug=n.data.slug||null)}}catch{}return o.set(e,{row:r,fetchedAt:Date.now()}),r}function s(e,t){return`
  <div data-cms-legal-footer="true" style="margin-top:24px;padding:18px 20px;border-top:1px solid #e2e8f0;background:#f8fafc;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Helvetica,Arial,sans-serif;color:#64748b;font-size:10px;line-height:1.55;text-align:left;">
    <div style="margin:0 0 8px 0;">${e}</div>
    <div style="margin:0;">${t}</div>
  </div>`}function l(e,t){if(e.includes('data-cms-legal-footer="true"'))return e;let n=function(e){let t=i(process.env.PLATFORM_BRAND_NAME||"CateringMS"),n=(0,r.eF)(null,e);return s(i((0,r.t$)(null)),`This message is subject to the ${t} <a href="${i(n)}" style="color:#475569;text-decoration:underline;font-weight:600;">Terms &amp; Conditions</a>.`)}(t);return/<\/body>/i.test(e)?e.replace(/<\/body>/i,`${n}</body>`):`${e}${n}`}async function c(e,t){if(e.includes('data-cms-legal-footer="true"'))return e;let n=await a(t.companyId,t.client),o=function(e){let t=e.companySlug||e.companyId,n=(0,r.eF)(t,e.origin);return s(i((0,r.t$)(e.confidentialityNotice)).replace(/\r?\n/g,"<br>"),`Client communications are subject to the caterer&rsquo;s <a href="${i(n)}" style="color:#475569;text-decoration:underline;font-weight:600;">Terms &amp; Conditions</a>.`)}({companyId:t.companyId,companySlug:n.slug,confidentialityNotice:n.confidentiality_notice,origin:t.origin});return/<\/body>/i.test(e)?e.replace(/<\/body>/i,`${o}</body>`):`${e}${o}`}}};var t=require("../../webpack-api-runtime.js");t.C(e);var n=e=>t(t.s=e),r=t.X(0,[28560],()=>n(26780));module.exports=r})();