import type { ChatNavigationRef } from "./navigation";

// The page catalog is deliberately hand-written. A route tells the assistant
// where a user can go; its description tells the assistant why that page is
// the right destination. Dynamic record links are still produced from live
// context and are not hard-coded here.
const ADMIN = ["super_admin", "owner", "company_admin", "region_admin", "sales_admin", "admin"];
const FINANCE = ["super_admin", "owner", "company_admin"];
const PLATFORM = ["super_admin"];
const KITCHEN = ["kitchen_manager", "kitchen_staff"];
const SHOPPING = ["shopping_staff", "shopping"];
const DRIVER = ["driver"];
const CLEANING = ["cleaning_manager", "cleaning_staff"];
const CLIENT = ["client"];

function page(
  ref: string,
  label: string,
  href: string,
  description: string,
  keywords: string[],
  roles: string[],
): ChatNavigationRef {
  return { ref, label, href, description, keywords, roles };
}

/**
 * Manually curated page-level vocabulary for Phase 2. Keep this list aligned
 * with src/pages. It gives RAG answers a stable destination even when a page
 * has no visible heading or its content is still loading.
 */
export const PAGE_NAVIGATION_REFS: ChatNavigationRef[] = [
  // Admin - CRM and revenue
  page("admin.client-search", "Client search", "/admin/client-search", "Search the client book and open a customer record", ["client search", "find client", "find customer", "search customer"], ADMIN),
  page("admin.company-profile", "Company profile", "/admin/company-profile", "Company identity, contact details, operating defaults, and branding settings", ["company profile", "business details", "company details"], ADMIN),
  page("admin.leads.new", "New lead", "/admin/leads/new", "Capture a new enquiry and start the sales follow-up", ["new lead", "add lead", "create enquiry", "new enquiry"], ADMIN),
  page("admin.quotes.new", "New quote", "/admin/quotes/new", "Build a quote from client, event, menu, equipment, and pricing details", ["new quote", "create quote", "quote builder", "build quote"], ADMIN),
  page("admin.orders.delivery-sheet", "Delivery sheet", "/admin/orders/delivery-sheet", "Prepare the delivery sheet for confirmed orders", ["delivery sheet", "delivery paperwork", "order delivery sheet"], ADMIN),
  page("admin.order-assignments", "Order assignments", "/admin/order-assignments", "Assign confirmed orders to kitchen, drivers, and service staff", ["assign order", "order assignment", "allocate order", "staff assignment"], ADMIN),
  page("admin.dispatch", "Dispatch", "/admin/dispatch", "Coordinate dispatch work and delivery readiness", ["dispatch", "dispatch work", "dispatch operations"], ADMIN),
  page("admin.dispatch-queue", "Dispatch queue", "/admin/dispatch-queue", "Review orders waiting to be dispatched", ["dispatch queue", "waiting dispatch", "unassigned delivery"], ADMIN),
  page("admin.live-operations", "Live operations", "/admin/live-operations", "Monitor active events and operational exceptions in real time", ["live operations", "operations now", "active events", "operational status"], ADMIN),
  page("admin.tracking", "Operations tracking", "/admin/tracking", "View live driver locations and delivery progress", ["track drivers", "track deliveries", "operations tracking", "live map"], ADMIN),
  page("admin.outstanding-balances", "Outstanding balances", "/admin/outstanding-balances", "Find unpaid client balances and payment follow-ups", ["outstanding balance", "unpaid balance", "money owed", "debtor"], FINANCE),
  page("admin.recurring-invoices", "Recurring invoices", "/admin/recurring-invoices", "Manage recurring billing schedules", ["recurring invoice", "repeat invoice", "subscription invoice"], FINANCE),
  page("admin.refunds", "Refunds", "/admin/refunds", "Review and manage customer refunds", ["refund", "refunds", "return payment"], FINANCE),
  page("admin.payables", "Payables", "/admin/payables", "Track supplier and operating payments due", ["payables", "supplier payment", "payments due", "accounts payable"], FINANCE),
  page("admin.cashflow-dashboard", "Cashflow dashboard", "/admin/cashflow-dashboard", "Review incoming, outgoing, and projected cash movement", ["cashflow", "cash flow", "money in", "money out", "forecast cash"], FINANCE),
  page("admin.financial-dashboard", "Financial dashboard", "/admin/financial-dashboard", "Review revenue, margin, costs, and financial performance", ["financial dashboard", "finance report", "profit", "margin", "financial performance"], FINANCE),
  page("admin.money-health", "Money health", "/admin/money-health", "See the business money-health summary and risks", ["money health", "financial health", "business health"], FINANCE),
  page("admin.fixed-costs", "Fixed costs", "/admin/fixed-costs", "Maintain recurring business costs used in financial planning", ["fixed costs", "overheads", "recurring costs"], FINANCE),
  page("admin.wages", "Wages", "/admin/wages", "Review staff wages and payment summaries", ["wages", "staff pay", "payroll summary"], FINANCE),
  page("admin.staff-hours", "Staff hours", "/admin/staff-hours", "Review clocked hours and the staff payment ledger", ["staff hours", "timesheets", "hours worked", "payment ledger"], FINANCE),
  page("admin.driver-settlement", "Driver settlement", "/admin/driver-settlement", "Review driver delivery and settlement amounts", ["driver settlement", "driver pay", "delivery settlement"], FINANCE),
  page("admin.kitchen-settlement", "Kitchen settlement", "/admin/kitchen-settlement", "Review kitchen staff settlement information", ["kitchen settlement", "kitchen pay"], FINANCE),

  // Admin - operations and configuration
  page("admin.stock", "Stock", "/admin/stock", "Review stock movements, counts, and adjustments", ["stock page", "stock movements", "stock count", "adjust stock"], ADMIN),
  page("admin.inventory-recipes", "Inventory recipes", "/admin/inventory-recipes", "Manage recipes and ingredient usage", ["recipes", "recipe ingredients", "food cost recipe"], ADMIN),
  page("admin.inventory-tracking", "Inventory tracking", "/admin/inventory-tracking", "Trace stock usage, movements, and inventory history", ["inventory tracking", "stock history", "inventory movements"], ADMIN),
  page("admin.suppliers", "Suppliers", "/admin/suppliers", "Manage supplier records and purchasing relationships", ["supplier management", "supplier records", "vendor management"], ADMIN),
  page("admin.equipment-damages", "Equipment damages", "/admin/equipment-damages", "Review damaged, missing, and repair-needed equipment", ["equipment damage", "broken equipment", "lost equipment", "repair equipment"], ADMIN),
  page("admin.vehicles", "Vehicles", "/admin/vehicles", "Manage delivery vehicles and availability", ["vehicles", "delivery vans", "vehicle availability"], ADMIN),
  page("admin.driver-management", "Driver management", "/admin/driver-management", "Manage driver profiles, status, and assignments", ["driver management", "drivers", "driver profile"], ADMIN),
  page("admin.driver-schedule", "Driver schedule", "/admin/driver-schedule", "Plan driver shifts and delivery coverage", ["driver schedule", "driver shifts", "schedule driver"], ADMIN),
  page("admin.cleaning-schedule", "Cleaning schedule", "/admin/cleaning-schedule", "Plan cleaning work around event and equipment returns", ["cleaning schedule", "schedule cleaning", "cleaning rota"], ADMIN),
  page("admin.kitchen-schedule", "Kitchen schedule", "/admin/kitchen-schedule", "Plan kitchen staffing and production coverage", ["kitchen schedule", "schedule kitchen", "kitchen rota"], ADMIN),
  page("admin.kitchen-duty-tracking", "Kitchen duty tracking", "/admin/kitchen-duty-tracking", "Track kitchen duty completion and handoffs", ["kitchen duty", "duty tracking", "kitchen checklist"], ADMIN),
  page("admin.kitchen-staff", "Kitchen staff", "/admin/kitchen-staff", "Manage kitchen staff and their operating access", ["kitchen team", "kitchen staff"], ADMIN),
  page("admin.kitchen-settings", "Kitchen settings", "/admin/kitchen-settings", "Configure kitchen operating defaults", ["kitchen configuration", "kitchen settings"], ADMIN),
  page("admin.teams", "Teams", "/admin/teams", "View operational teams and staffing coverage", ["teams", "team management", "staff teams"], ADMIN),
  page("admin.teams.kitchen", "Kitchen team", "/admin/teams/kitchen", "Manage the kitchen team roster and prep schedule", ["kitchen team roster", "kitchen staffing"], ADMIN),
  page("admin.teams.drivers", "Driver team", "/admin/teams/drivers", "Manage the driver team roster and availability", ["driver team roster", "driver staffing"], ADMIN),
  page("admin.teams.shopping", "Shopping team", "/admin/teams/shopping", "Manage the shopping team roster and coverage", ["shopping team roster", "shopping staffing"], ADMIN),
  page("admin.teams.cleaning", "Cleaning team", "/admin/teams/cleaning", "Manage the cleaning team roster and coverage", ["cleaning team roster", "cleaning staffing"], ADMIN),
  page("admin.public-holidays", "Public holidays", "/admin/public-holidays", "Maintain holidays used in planning and scheduling", ["public holidays", "holidays", "holiday calendar"], ADMIN),
  page("admin.regions", "Regions", "/admin/regions", "Manage branches, regions, and operational boundaries", ["regions", "branches", "branch management"], ADMIN),
  page("admin.users", "Users and access", "/admin/users", "Manage user accounts, roles, and invitations", ["users", "user access", "roles", "invitations", "permissions"], ADMIN),
  page("admin.staff", "Staff", "/admin/staff", "Manage staff records and operational access", ["staff records", "staff management", "employees"], ADMIN),
  page("admin.audit-logs", "Audit logs", "/admin/audit-logs", "Review recorded changes and security activity", ["audit log", "audit trail", "who changed", "security log"], ADMIN),
  page("admin.notifications", "Admin notifications", "/admin/notifications", "Review operational alerts and internal notifications", ["admin alerts", "admin notifications", "internal alerts"], ADMIN),
  page("admin.notification-settings", "Notification settings", "/admin/notification-settings", "Configure which operational notifications are sent", ["notification settings", "alert settings", "notification preferences"], ADMIN),
  page("admin.email-settings", "Email settings", "/admin/email-settings", "Configure outbound email delivery for the company", ["email settings", "email provider", "configure email", "resend", "smtp"], ADMIN),
  page("admin.email-templates", "Email templates", "/admin/email-templates", "Manage reusable email templates, automation, and sent logs", ["email templates", "email automation", "sent log", "template"], ADMIN),
  page("admin.messaging-templates", "Messaging templates", "/admin/messaging-templates", "Manage reusable operational message templates", ["messaging templates", "message templates", "sms template"], ADMIN),
  page("admin.integrations", "Integrations", "/admin/integrations", "Connect and manage external services", ["integrations", "connect service", "external integration"], ADMIN),
  page("admin.integrations.embed", "Embed integrations", "/admin/integrations/embed", "Manage public embed forms and integration snippets", ["embed forms", "embedded form", "integration embed"], ADMIN),
  page("admin.integrations.embed.new", "New embed form", "/admin/integrations/embed/new", "Create a public enquiry or lead capture embed form", ["new embed", "create embed form", "lead capture form"], ADMIN),
  page("admin.payment-gateways", "Payment gateways", "/admin/payment-gateways", "Configure payment providers and payment collection", ["payment gateway", "payment provider", "online payments"], ADMIN),
  page("admin.offering", "Offering", "/admin/offering", "Manage the services and products offered to clients", ["offering", "services", "products offered", "service catalog"], ADMIN),
  page("admin.menu", "Menu", "/admin/menu", "Manage menu items and catering menu structure", ["menu", "menu items", "catering menu"], ADMIN),
  page("admin.package", "Package settings", "/admin/package", "Configure catering package defaults", ["package settings", "catering package"], ADMIN),
  page("admin.packages", "Packages", "/admin/packages", "Manage reusable catering packages", ["packages", "package catalog", "package management"], ADMIN),
  page("admin.subscription", "Subscription", "/admin/subscription", "Review the current company subscription", ["subscription", "plan", "billing plan"], FINANCE),
  page("admin.white-label", "White label", "/admin/white-label", "Configure customer-facing brand and white-label settings", ["white label", "branding", "brand settings"], ADMIN),
  page("admin.hr-solutions", "HR solutions", "/admin/hr-solutions", "Review HR tools and staff administration options", ["hr", "human resources", "hr solutions"], ADMIN),
  page("admin.reviews", "Reviews", "/admin/reviews", "Review customer feedback and published reviews", ["reviews", "customer reviews", "ratings"], ADMIN),
  page("admin.tax-purchases", "Tax and purchases", "/admin/tax-purchases", "Review purchase tax information and tax-ready records", ["tax purchases", "purchase tax", "vat purchases"], FINANCE),
  page("admin.outsource-providers", "Outsource providers", "/admin/outsource-providers", "Manage external service providers used for event fulfilment", ["outsource providers", "external providers", "hire in providers"], ADMIN),
  page("admin.onboarding", "Onboarding", "/admin/onboarding", "Set up company data, clients, and initial operating configuration", ["onboarding", "setup", "company setup"], ADMIN),
  page("admin.onboarding.import", "Import data", "/admin/onboarding/import", "Import initial business data into CateringMS", ["import data", "data import", "csv import"], ADMIN),
  page("admin.onboarding.imports", "Import history", "/admin/onboarding/imports", "Review previous data imports and their results", ["import history", "previous imports"], ADMIN),
  page("admin.onboarding.clients", "Import clients", "/admin/onboarding/clients", "Import and validate the initial client book", ["import clients", "client import"], ADMIN),
  page("admin.onboarding.receipts", "Import receipts", "/admin/onboarding/receipts", "Import historical purchase receipts", ["import receipts", "receipt import"], ADMIN),
  page("admin.settings", "Admin settings", "/admin/settings", "Open the central company configuration area", ["admin settings", "settings"], ADMIN),
  page("admin.ai-brain", "AI brain", "/admin/ai-brain", "Manage approved assistant documents and knowledge sources", ["ai brain", "assistant knowledge", "rag", "resync knowledge"], FINANCE),
  page("admin.ai-brain.access", "AI access", "/admin/ai-brain/access", "Manage role access and create read-only assistant tools", ["ai access", "assistant permissions", "live data access", "tool access", "custom tools"], FINANCE),

  // Team portals
  page("kitchen.dashboard", "Kitchen dashboard", "/team-portal/kitchen/dashboard", "Kitchen workload, readiness, and production overview", ["kitchen dashboard", "kitchen overview"], KITCHEN),
  page("kitchen.duty", "Kitchen duty", "/team-portal/kitchen/duty", "Kitchen duty assignments and completion", ["kitchen duty", "my kitchen duty"], KITCHEN),
  page("kitchen.handovers", "Kitchen handovers", "/team-portal/kitchen/handovers", "Kitchen handover notes between shifts", ["kitchen handover", "handover kitchen"], KITCHEN),
  page("kitchen.menu", "Kitchen menu", "/team-portal/kitchen/menu", "Kitchen menu and production reference", ["kitchen menu", "menu kitchen"], KITCHEN),
  page("kitchen.settings", "Kitchen portal settings", "/team-portal/kitchen/settings", "Personal kitchen workspace settings", ["kitchen portal settings"], KITCHEN),
  page("kitchen.notifications", "Kitchen notifications", "/team-portal/kitchen/notifications", "Notifications relevant to kitchen work", ["kitchen notifications"], KITCHEN),
  page("kitchen.management", "Kitchen team management", "/team-portal/kitchen/management", "Manage the kitchen roster, clock-ins, and daily work notes", ["kitchen team management", "manage kitchen team", "kitchen manager", "kitchen diary"], ["kitchen_manager"]),
  page("shopping.dashboard", "Shopping dashboard", "/team-portal/shopping/dashboard", "Purchasing workload, shortages, and buying overview", ["shopping dashboard", "shopping overview"], SHOPPING),
  page("shopping.alerts", "Shopping alerts", "/team-portal/shopping/alerts", "Procurement alerts and stock shortages", ["shopping alerts", "purchase alerts", "shortage alerts"], SHOPPING),
  page("shopping.invoices", "Shopping invoices", "/team-portal/shopping/invoices", "Supplier invoices and purchasing spend history", ["shopping invoices", "supplier invoices", "purchasing spend"], SHOPPING),
  page("shopping.kitchen-demand", "Kitchen demand", "/team-portal/shopping/kitchen-demand", "Upcoming kitchen demand used to plan purchases", ["kitchen demand", "purchase demand", "ingredient demand"], SHOPPING),
  page("shopping.orders", "Shopping orders", "/team-portal/shopping/orders", "Purchase orders and supplier order status", ["shopping orders", "purchase orders", "supplier orders"], SHOPPING),
  page("shopping.receipts", "Shopping receipts", "/team-portal/shopping/receipts", "Record and review purchasing receipts", ["shopping receipts", "purchase receipts"], SHOPPING),
  page("shopping.restock", "Restock", "/team-portal/shopping/restock", "Restock items that are below their par level", ["restock", "restock list", "par level"], SHOPPING),
  page("shopping.settings", "Shopping settings", "/team-portal/shopping/settings", "Personal shopping workspace settings", ["shopping settings"], SHOPPING),
  page("shopping.notifications", "Shopping notifications", "/team-portal/shopping/notifications", "Notifications relevant to purchasing work", ["shopping notifications"], SHOPPING),
  page("driver.calendar", "Driver calendar", "/team-portal/driver/calendar", "Driver schedule and assigned event dates", ["driver calendar", "driver dates"], DRIVER),
  page("driver.schedule", "Driver schedule", "/team-portal/driver/schedule", "Your scheduled driving shifts", ["my driver schedule", "my shifts"], DRIVER),
  page("driver.earnings", "Driver earnings", "/team-portal/driver/earnings", "Your shift and delivery earnings", ["driver earnings", "my earnings", "driver pay"], DRIVER),
  page("driver.notifications", "Driver notifications", "/team-portal/driver/notifications", "Notifications relevant to your driving work", ["driver notifications"], DRIVER),
  page("cleaning.equipment", "Cleaning equipment", "/team-portal/cleaning/equipment", "Equipment cleaning and condition work", ["cleaning equipment", "equipment condition"], CLEANING),
  page("cleaning.handovers", "Cleaning handovers", "/team-portal/cleaning/dashboard", "Open the cleaning dashboard to review shift handovers; a specific handover opens from its record", ["cleaning handover", "handover cleaning", "shift handover"], CLEANING),
  page("cleaning.notifications", "Cleaning notifications", "/team-portal/cleaning/notifications", "Notifications relevant to cleaning work", ["cleaning notifications"], CLEANING),
  page("cleaning.schedules", "Cleaning schedules", "/team-portal/cleaning/schedules", "Your scheduled cleaning work", ["cleaning schedule", "my cleaning schedule"], CLEANING),
  page("cleaning.settings", "Cleaning settings", "/team-portal/cleaning/settings", "Personal cleaning workspace settings", ["cleaning settings"], CLEANING),
  page("cleaning.supplies", "Cleaning supplies", "/team-portal/cleaning/supplies", "Cleaning supplies and replenishment needs", ["cleaning supplies", "cleaning stock"], CLEANING),
  page("cleaning.workflows", "Cleaning workflows", "/team-portal/cleaning/workflows", "Cleaning workflow guidance and completion steps", ["cleaning workflows", "cleaning process"], CLEANING),
  page("cleaning.management", "Cleaning team management", "/team-portal/cleaning/management", "Manage the cleaning roster, clock-ins, and daily work notes", ["cleaning team management", "manage cleaning team", "cleaning manager", "cleaning diary"], ["cleaning_manager"]),
  page("general.job-progress", "Job progress", "/team-portal/general/job-progress", "Shared job progress and handoff status", ["job progress", "work progress", "job status"], ["staff", ...ADMIN]),
  page("waiter.dashboard", "Waiter dashboard", "/team-portal/waiter/dashboard", "Service team work overview", ["waiter dashboard", "service dashboard"], ["waiter"]),
  page("waiter.notifications", "Waiter notifications", "/team-portal/waiter/notifications", "Notifications relevant to service work", ["waiter notifications"], ["waiter"]),

  // Client portal
  page("client.quotes", "My quotes", "/client-portal/quotes", "Quotes prepared for your events", ["my quotes", "client quotes", "quote from caterer"], CLIENT),
  page("client.profile", "My profile", "/client-portal/profile", "Your contact and account details", ["my profile", "profile details", "account details"], CLIENT),
  page("client.notifications", "Client notifications", "/client-portal/notifications", "Updates about your events, orders, and payments", ["client notifications", "my alerts"], CLIENT),
  page("client.portal", "Client portal", "/client-portal", "Open the client workspace entry point", ["client portal", "customer portal", "client workspace"], CLIENT),
  page("client.subscription-invoices", "Subscription invoices", "/client/subscription-invoices", "Review subscription invoice records available to the client account", ["subscription invoices", "client subscription billing"], CLIENT),

  // Shared account and portal entry points
  page("account.achievements", "Achievements", "/account/achievements", "Review personal milestones and achievements", ["achievements", "milestones", "my achievements"], ["super_admin", "owner", "company_admin", "region_admin", "sales_admin", "admin", "kitchen_manager", "kitchen_staff", "shopping_staff", "shopping", "driver", "waiter", "cleaning_manager", "cleaning_staff", "client", "staff"]),
  page("account.settings", "Account settings", "/account/settings", "Manage personal profile, security, privacy, and notifications", ["account settings", "personal settings", "profile settings", "security settings"], ["super_admin", "owner", "company_admin", "region_admin", "sales_admin", "admin", "kitchen_manager", "kitchen_staff", "shopping_staff", "shopping", "driver", "waiter", "cleaning_manager", "cleaning_staff", "client", "staff"]),
  page("admin.clients", "Admin clients", "/admin/clients", "Open the admin client workspace", ["admin clients", "client administration", "manage clients"], ADMIN),
  page("team-portal.cleaning", "Cleaning portal", "/team-portal/cleaning", "Open the cleaning team workspace", ["cleaning portal", "cleaning workspace"], CLEANING),
  page("team-portal.driver", "Driver portal", "/team-portal/driver", "Open the driver team workspace", ["driver portal", "driver workspace"], DRIVER),
  page("team-portal.kitchen", "Kitchen portal", "/team-portal/kitchen", "Open the kitchen team workspace", ["kitchen portal", "kitchen workspace"], KITCHEN),
  page("team-portal.shopping", "Shopping portal", "/team-portal/shopping", "Open the shopping team workspace", ["shopping portal", "shopping workspace"], SHOPPING),
  page("team-portal.waiter", "Waiter portal", "/team-portal/waiter", "Open the service team workspace", ["waiter portal", "service workspace"], ["waiter"]),

  // Platform-owner pages
  page("platform.index", "Platform workspace", "/admin/platform", "Platform-owner workspace for cross-company administration", ["platform workspace", "platform admin"], PLATFORM),
  page("platform.dashboard", "Platform dashboard", "/admin/platform/dashboard", "Cross-company platform health and performance overview", ["platform dashboard", "platform overview", "all companies"], PLATFORM),
  page("platform.financial-dashboard", "Platform financial dashboard", "/admin/platform/financial-dashboard", "Review cross-company platform financial performance, MRR, ARR, churn, and subscription revenue", ["platform finance", "platform financial dashboard", "mrr", "monthly recurring revenue", "recurring revenue", "arr", "annual recurring revenue", "subscription revenue", "churn rate"], PLATFORM),
  page("platform.company-database", "Company records", "/admin/platform/company-database", "Platform-wide company records", ["company records", "all companies", "registered companies"], PLATFORM),
  page("platform.tenant-health", "Company health", "/admin/platform/tenant-health", "Monitor company health and configuration issues", ["company health", "company status", "setup issues"], PLATFORM),
  page("platform.payment-issues", "Payment issues", "/admin/platform/payment-issues", "Review companies whose payment setup needs attention", ["payment issues", "payment gateway issues", "payment setup"], PLATFORM),
  page("platform.user-management", "Platform user management", "/admin/platform/user-management", "Manage user access across companies", ["platform users", "platform user management", "company users"], PLATFORM),
  page("platform.subscription-management", "Subscription management", "/admin/platform/subscription-management", "Manage subscriptions across companies", ["subscription", "subscriptions", "manage subscriptions", "platform subscriptions"], PLATFORM),
  page("platform.pricing-management", "Pricing management", "/admin/platform/pricing-management", "Manage platform pricing and plan rules", ["pricing management", "platform pricing", "plans pricing"], PLATFORM),
  page("platform.tax-rules", "Tax rules", "/admin/platform/tax-rules", "Manage platform tax rules", ["tax rules", "platform tax"], PLATFORM),
  page("platform.currency-monitoring", "Currency monitoring", "/admin/platform/currency-monitoring", "Monitor supported currencies, exchange rates, and pricing behavior", ["currency monitoring", "currency settings", "currency", "currencies", "supported currencies", "exchange rates", "currency monitor"], PLATFORM),
  page("platform.tech-costs", "Tech-stack costs", "/admin/platform/tech-costs", "Review estimated technology costs, cost per company, service breakdown, margin, and scaling", ["technology costs", "tech costs", "tech-stack costs", "service costs", "operating costs", "platform cost", "infrastructure cost", "tenant cost", "cost per tenant", "margin analysis", "cost trend"], PLATFORM),
  page("platform.cms-pages", "CMS pages", "/admin/platform/cms-pages", "Create and manage public content pages", ["cms pages", "content pages", "website pages"], PLATFORM),
  page("platform.cms-blog", "CMS blog", "/admin/platform/cms-blog", "Create and manage public blog content", ["cms blog", "blog", "blog posts"], PLATFORM),
  page("platform.messaging-templates", "Platform messaging templates", "/admin/platform/messaging-templates", "Manage platform-wide message templates", ["platform message templates"], PLATFORM),
  page("platform.settings", "Platform settings", "/admin/platform/settings", "Manage platform-level configuration", ["platform settings", "system settings"], PLATFORM),
  page("platform.audit-logs", "Platform audit logs", "/admin/platform/audit-logs", "Review platform-wide audit activity", ["platform audit", "platform audit logs"], PLATFORM),
  page("platform.running-todo", "Platform running todo", "/admin/platform/running-todo", "Review platform delivery and maintenance work", ["platform todo", "running todo", "platform backlog"], PLATFORM),
  page("platform.trial-management", "Trial management", "/admin/platform/trial-management", "Manage company trials and trial conversion", ["trial management", "company trials"], PLATFORM),
  page("super-admin", "Super admin workspace", "/super-admin", "Open the platform owner workspace", ["super admin", "platform owner workspace"], PLATFORM),
  page("super-admin.admin-dashboard", "Super admin dashboard", "/super-admin/admin/dashboard", "Review platform administration and company health", ["super admin dashboard", "platform administration"], PLATFORM),
];

function section(
  ref: string,
  label: string,
  href: string,
  description: string,
  keywords: string[],
  roles: string[],
): ChatNavigationRef {
  return { ref, label, href, description, keywords, roles, targetType: "section" };
}

/** Stable, manually described high-value targets inside pages. */
export const SECTION_NAVIGATION_REFS: ChatNavigationRef[] = [
  section("admin.contacts.filters", "Contact filters", "/admin/contacts#contact-filters", "Search the contact book and filter by lifecycle, tags, or saved view", ["contact filters", "filter contacts", "contact search", "saved contact view"], ADMIN),
  section("admin.contacts.book", "Contact book", "/admin/contacts#contact-book", "Review the filtered client and lead contact records", ["contact book", "contact list", "client list", "customer list"], ADMIN),
  section("admin.leads.filters", "Lead filters", "/admin/leads#lead-filters", "Search the sales pipeline and filter by lead status", ["lead filters", "filter leads", "lead search", "pipeline filter"], ADMIN),
  section("admin.leads.pipeline", "Lead pipeline", "/admin/leads#lead-pipeline", "Review active enquiries, follow-ups, quotes, and conversions", ["lead pipeline", "sales pipeline", "enquiries list", "lead list"], ADMIN),
  section("admin.quotes.regions", "Quotes by region", "/admin/quotes#quote-regions", "Jump between quote groups for different branches or regions", ["quotes by region", "quote region", "branch quotes"], ADMIN),
  section("admin.quotes.pipeline", "Quote pipeline", "/admin/quotes#quote-pipeline", "Review quote KPIs, filters, and quotes needing action", ["quote pipeline", "quote list", "quotes needing action"], ADMIN),
  section("admin.orders.filters", "Order filters", "/admin/orders#order-filters", "Filter orders by status, date, owner, and saved view", ["order filters", "filter orders", "order search"], ADMIN),
  section("admin.orders.list", "Order list", "/admin/orders#order-list", "Review confirmed bookings and their operational timelines", ["order list", "booking list", "confirmed bookings"], ADMIN),
  section("admin.invoices.filters", "Invoice filters", "/admin/invoices#invoice-filters", "Filter the invoice ledger by payment status, date, amount, or client", ["invoice filters", "filter invoices", "invoice search"], FINANCE),
  section("admin.invoices.ledger", "Invoice ledger", "/admin/invoices#invoice-ledger", "Review invoice records, balances, payment status, and follow-up actions", ["invoice ledger", "invoice list", "receivables ledger"], FINANCE),
  section("admin.inventory.filters", "Inventory filters", "/admin/inventory#inventory-filters", "Search and filter stock items by category or status", ["inventory filters", "filter inventory", "stock search"], ADMIN),
  section("admin.inventory.catalogue", "Inventory catalogue", "/admin/inventory#inventory-catalogue", "Review stock items, quantities, reorder levels, and item records", ["inventory catalogue", "inventory list", "stock catalogue"], ADMIN),
  section("admin.shopping.buy-now", "Buy now list", "/admin/shopping?tab=buy_now#shopping-buy-now", "Items below threshold that need urgent purchasing", ["buy now", "urgent shopping", "stock shortfall"], ADMIN),
  section("admin.shopping.plan", "Shopping plan", "/admin/shopping?tab=plan#shopping-plan", "Plan purchases against upcoming events and demand", ["shopping plan", "purchase planning", "event demand"], ADMIN),
  section("admin.shopping.suppliers", "Supplier comparison", "/admin/shopping?tab=supplier#shopping-suppliers", "Compare supplier options and linked purchase items", ["supplier comparison", "supplier prices"], ADMIN),
  section("admin.shopping.receipts", "Receipt history", "/admin/shopping?tab=receipts#shopping-receipts", "Review purchase receipts and recorded spend", ["receipt history", "purchase receipts"], ADMIN),
  section("admin.tracking.map", "Tracking map", "/admin/tracking?view=map#tracking-map", "See active delivery locations on the live operations map", ["tracking map", "live tracking map", "driver map"], ADMIN),
  section("admin.tracking.list", "Tracking list", "/admin/tracking?view=list#tracking-list", "Review active deliveries in a searchable list", ["tracking list", "delivery tracking list"], ADMIN),
  section("admin.email-templates.templates", "Email templates", "/admin/email-templates?tab=templates#email-templates", "Edit reusable email copy used by the team", ["email templates", "edit email template"], ADMIN),
  section("admin.email-templates.sent-log", "Sent email log", "/admin/email-templates?tab=sent-log#email-sent-log", "Review emails sent through the platform", ["sent email log", "email history", "sent emails"], ADMIN),
  section("admin.email-templates.automation", "Email automation", "/admin/email-templates?tab=automation#email-automation", "Review automated email triggers and rules", ["email automation", "automated emails", "email triggers"], ADMIN),
  section("admin.email-templates.settings", "Email template settings", "/admin/email-templates?tab=settings#email-settings", "Configure email template behavior and defaults", ["email template settings"], ADMIN),
  section("kitchen.production.board", "Production board", "/team-portal/kitchen/production#production-board", "See production work by day, order, and readiness state", ["production board", "kitchen production board", "production schedule"], KITCHEN),
  section("kitchen.prep.demand", "Prep demand", "/team-portal/kitchen/prep-list#prep-demand", "Compare upcoming ingredient demand with stock on hand", ["prep demand", "ingredient demand", "prep shortages"], KITCHEN),
  section("shopping.buy-list.items", "Items to buy", "/team-portal/shopping/buy-list#shopping-buy-items", "Review the current purchasing list and its priority filters", ["items to buy", "shopping items", "buy list items"], SHOPPING),
  section("shopping.inventory.stock", "Procurement stock", "/team-portal/shopping/inventory#shopping-stock", "Review inventory quantities, out-of-stock items, and stock value", ["procurement stock", "out of stock", "shopping stock"], SHOPPING),
  section("driver.deliveries.history", "Delivery history", "/team-portal/driver/deliveries#delivery-history", "Review all, upcoming, or completed assigned deliveries", ["delivery history", "my deliveries", "delivery list"], DRIVER),
  section("cleaning.dashboard.verification", "Equipment verification", "/team-portal/cleaning/dashboard?tab=verification#cleaning-verification", "Verify returned equipment and readiness after an event", ["equipment verification", "verify returns", "returned equipment"], CLEANING),
  section("cleaning.dashboard.damages", "Cleaning damages", "/team-portal/cleaning/dashboard?tab=damages#cleaning-damages", "Review damaged or missing equipment flagged by the cleaning team", ["cleaning damages", "damaged equipment", "losses"], CLEANING),
  section("client.bookings.list", "Bookings list", "/client-portal/my-orders#booking-list", "Review active and completed bookings with their next actions", ["bookings list", "my bookings", "booking history"], CLIENT),
  section("client.quotes.waiting", "Quotes waiting for response", "/client-portal/quotes#quotes-waiting", "Open quotes that need your accept, decline, or change request", ["quotes waiting", "quote response", "accept quote"], CLIENT),
  section("client.billing.invoices", "Client invoice list", "/client-portal/billing#invoice-list", "Review invoices, balances, payment status, and payment actions", ["client invoices", "my invoice list", "billing list"], CLIENT),
  section("client.tracking.live", "Live trips", "/client-portal/tracking#live-trips", "Track active delivery trips and their latest progress", ["live trips", "live delivery", "delivery progress"], CLIENT),
  section("admin.ai-brain.access.live-tools", "Live-data tools", "/admin/ai-brain/access#live-data-access", "Manage role access and create read-only assistant tools for current questions", ["live data tools", "assistant tools", "role tools", "tool permissions", "custom tools"], FINANCE),
  section("platform.tech-costs.tenant-cost", "Cost per company", "/admin/platform/tech-costs#tenant-cost", "Review the estimated average technology cost for each platform company", ["tenant cost", "cost per tenant", "average cost per tenant"], PLATFORM),
  section("platform.tech-costs.margin", "Margin analysis", "/admin/platform/tech-costs#margin-analysis", "Compare estimated platform technology costs with subscription revenue", ["margin analysis", "technology margin", "cost margin"], PLATFORM),
  section("platform.tech-costs.trend", "Cost trend", "/admin/platform/tech-costs#cost-trend", "Review cost-at-scale scenarios and available technology-cost history", ["cost trend", "technology cost trend", "cost history"], PLATFORM),
  section("platform.company-database.trials", "Trial companies", "/admin/platform/company-database?status=trial#company-records", "Open company records filtered to companies on trial", ["trial companies", "companies on trial", "trial records"], PLATFORM),
  section("platform.company-database.records", "Company records", "/admin/platform/company-database#company-records", "Review the platform company directory and open a company record", ["company records", "company directory"], PLATFORM),
  section("platform.tenant-health.onboarding", "Stuck onboarding", "/admin/platform/tenant-health#stuck-onboarding", "Review companies that have not completed onboarding", ["stuck onboarding", "incomplete onboarding"], PLATFORM),
  section("platform.tenant-health.dormant", "Dormant companies", "/admin/platform/tenant-health#dormant-companies", "Review onboarded companies with no recent activity", ["dormant companies", "quiet companies"], PLATFORM),
  section("platform.tenant-health.new-signups", "New signups", "/admin/platform/tenant-health#new-signups", "Review recently created company records", ["new signups", "recent signups"], PLATFORM),
  section("platform.user-management.pending-invitations", "Pending invitations", "/admin/platform/user-management?status=pending#pending-invitations", "Review users who have not accepted their invitation", ["pending invitations", "invite pending", "unaccepted invites"], PLATFORM),
  section("platform.user-management.directory", "User directory", "/admin/platform/user-management#user-directory", "Review platform users and their company assignments", ["user directory", "platform users"], PLATFORM),
  section("platform.subscription-management.active-plans", "Active plans", "/admin/platform/subscription-management?status=active#active-plans", "Review companies on active paid subscriptions", ["active plans", "active subscriptions", "paid plans"], PLATFORM),
  section("platform.subscription-management.records", "Subscription records", "/admin/platform/subscription-management#subscription-records", "Review subscription records, statuses, amounts, and renewal dates", ["subscription records", "customer subscriptions"], PLATFORM),
  section("platform.financial-dashboard.churn", "Churn", "/admin/platform/financial-dashboard#churn", "Review the current churn metric and cancelled-company context", ["churn", "churn rate", "cancelled companies"], PLATFORM),
  section("platform.pricing-management.feature-gates", "Feature gates", "/admin/platform/pricing-management#feature-gates", "Review plan features and limits used by the platform", ["feature gates", "plan features", "included features", "plan limits"], PLATFORM),
  section("platform.currency-monitoring.alerts", "Currency alerts", "/admin/platform/currency-monitoring#currency-alerts", "Review unresolved exchange-rate threshold alerts", ["currency alerts", "exchange alerts", "threshold alerts"], PLATFORM),
  section("platform.ai-brain.approved-sources", "Approved knowledge", "/admin/ai-brain#approved-sources", "Review approved platform knowledge sources", ["approved knowledge", "approved sources", "platform sources"], PLATFORM),
  section("platform.ai-brain.sync-status", "Source sync status", "/admin/ai-brain#source-sync-status", "Review ready, pending, and failed source indexing status", ["source sync", "sync status", "indexing status"], PLATFORM),
  section("platform.ai-brain.failed-sources", "Failed sources", "/admin/ai-brain#failed-sources", "Review platform sources that failed indexing", ["failed sources", "source failures", "indexing failure"], PLATFORM),
  section("platform.ai-access.role-controls", "Role controls", "/admin/ai-brain/access#role-access-controls", "Review platform assistant access by role", ["role controls", "role access", "access settings"], PLATFORM),
  section("platform.audit-logs.filters.subscription", "Subscription audit filter", "/admin/platform/audit-logs?category=subscription&since=all#platform-audit-filters", "Open audit activity filtered to subscription changes", ["subscription audit", "subscription changes", "audit subscription filter"], PLATFORM),
  section("platform.audit-logs.filters.pricing", "Pricing audit filter", "/admin/platform/audit-logs?category=pricing&since=all#platform-audit-filters", "Open audit activity filtered to pricing changes", ["pricing audit", "pricing changes", "audit pricing filter"], PLATFORM),
  section("platform.audit-logs.filters.permissions", "Permission audit filter", "/admin/platform/audit-logs?category=permission&since=all#platform-audit-filters", "Open audit activity filtered to role and permission changes", ["permission audit", "permission changes", "role changes", "audit permission filter"], PLATFORM),
  section("platform.audit-logs.filters.company", "Company audit filter", "/admin/platform/audit-logs?category=company&since=all#platform-audit-filters", "Open platform activity filtered to company changes", ["company audit filter", "audit by company"], PLATFORM),
  section("platform.audit-logs.filters.user", "User audit filter", "/admin/platform/audit-logs?entityType=user&since=all#platform-audit-filters", "Open platform activity filtered to user records", ["user audit filter", "audit by user"], PLATFORM),
  section("platform.audit-logs.filters.action", "Action audit filter", "/admin/platform/audit-logs?since=all#platform-audit-filters", "Open the platform activity filters for a specific action", ["action audit filter", "audit by action"], PLATFORM),
  section("platform.audit-logs.filters.date", "Date audit filter", "/admin/platform/audit-logs?since=all#platform-audit-filters", "Open the platform activity filters for a selected date range", ["date audit filter", "audit by date"], PLATFORM),
  section("platform.audit-logs.filters.failure", "Failed activity filter", "/admin/platform/audit-logs?category=failure&since=all#platform-audit-filters", "Open failed, suspicious, or denied platform activity", ["failed activity", "failed actions", "suspicious actions"], PLATFORM),
  section("platform.audit-logs.filters", "Audit filters", "/admin/platform/audit-logs?since=all#platform-audit-filters", "Filter platform activity by company, user, action, or date", ["audit filters", "filter audit logs", "audit log filters"], PLATFORM),
  section("platform.audit-logs.record", "Audit record", "/admin/platform/audit-logs?since=all#platform-audit-records", "Review a specific platform activity record", ["audit record", "activity record", "specific change"], PLATFORM),
  section("platform.audit-logs.records", "Audit records", "/admin/platform/audit-logs?since=all#platform-audit-records", "Review the matching platform activity records", ["audit records", "activity records"], PLATFORM),
];
