ALTER TABLE equipment
ADD COLUMN IF NOT EXISTS quantity_total INT NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS category VARCHAR,
ADD COLUMN IF NOT EXISTS condition VARCHAR,
ADD COLUMN IF NOT EXISTS unit VARCHAR,
ADD COLUMN IF NOT EXISTS minimum_stock INT NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS shelf_life_days INT,
ADD COLUMN IF NOT EXISTS purchase_date DATE,
ADD COLUMN IF NOT EXISTS last_restocked DATE,
ADD COLUMN IF NOT EXISTS average_cost NUMERIC,
ADD COLUMN IF NOT EXISTS last_maintenance_date DATE;