// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ypwxsmytkvaefmmlkspf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlwd3hzbXl0a3ZhZWZtbWxrc3BmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAyMjc1ODEsImV4cCI6MjA3NTgwMzU4MX0.3DapqGeC_5qwINnUzy9Loz5bF1PygeVTS_2lAcJmK9w";

// Validate that URL and key are defined
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error("Supabase configuration is missing. Please check your environment variables.");
}

// Validate URL format
try {
  new URL(SUPABASE_URL);
} catch (error) {
  throw new Error(`Invalid Supabase URL: ${SUPABASE_URL}`);
}

// CRITICAL FIX: Aggressive session cleanup on login page
if (typeof window !== 'undefined') {
  const isLoginPage = window.location.pathname.includes('/auth/login');
  
  if (isLoginPage) {
    try {
      // Clear ALL auth-related storage immediately
      const projectRef = 'ypwxsmytkvaefmmlkspf';
      const storageKey = `sb-${projectRef}-auth-token`;
      
      // Remove the main auth token
      localStorage.removeItem(storageKey);
      
      // Clear any other Supabase auth keys
      Object.keys(localStorage).forEach(key => {
        if (key.startsWith('sb-') && key.includes('auth')) {
          localStorage.removeItem(key);
        }
      });
      
      // Clear session storage too
      sessionStorage.clear();
      
      console.log('✅ Cleared all auth data on login page');
    } catch (error) {
      console.warn('Error clearing auth data:', error);
    }
  }
}

// Smart cleanup: Only clear corrupted session data, not all Supabase data (for non-login pages)
if (typeof window !== 'undefined' && !window.location.pathname.includes('/auth/login')) {
  try {
    // Extract project ref safely
    let projectRef = 'ypwxsmytkvaefmmlkspf';
    try {
      const urlParts = SUPABASE_URL.split('//');
      if (urlParts[1]) {
        const hostParts = urlParts[1].split('.');
        if (hostParts[0]) {
          projectRef = hostParts[0];
        }
      }
    } catch (e) {
      console.warn('Could not parse project ref from URL, using default');
    }
    
    const storageKey = `sb-${projectRef}-auth-token`;
    
    // Only check and clear if data appears corrupted
    try {
      const storedData = localStorage.getItem(storageKey);
      
      if (storedData) {
        try {
          const parsed = JSON.parse(storedData);
          
          // Check if the data structure is valid
          if (!parsed || typeof parsed !== 'object') {
            console.warn('Clearing invalid session data structure');
            localStorage.removeItem(storageKey);
          } else if (parsed.access_token === undefined && parsed.refresh_token === undefined) {
            console.warn('Clearing session data with missing tokens');
            localStorage.removeItem(storageKey);
          }
        } catch (parseError) {
          console.warn('Clearing malformed session JSON');
          localStorage.removeItem(storageKey);
        }
      }
    } catch (storageError) {
      console.warn('Error checking session storage:', storageError);
    }
    
    // Clean up any malformed URL fragments
    try {
      const currentUrl = window.location.href;
      if (currentUrl.includes('#access_token') || currentUrl.includes('#error')) {
        const hash = window.location.hash;
        if (hash && hash.length > 1) {
          try {
            new URLSearchParams(hash.substring(1));
          } catch (hashError) {
            console.warn('Detected malformed auth hash, cleaning up');
            window.history.replaceState({}, document.title, window.location.pathname + window.location.search);
          }
        }
      }
    } catch (urlCleanupError) {
      console.warn('Error during URL cleanup:', urlCleanupError);
    }
  } catch (error) {
    console.error('Error during session validation:', error);
  }
}

// Create a safe storage implementation that handles errors gracefully
const createSafeStorage = () => {
  if (typeof window === 'undefined') {
    return undefined;
  }

  return {
    getItem: (key: string) => {
      try {
        return localStorage.getItem(key);
      } catch (e) {
        console.warn('Storage getItem error:', e);
        return null;
      }
    },
    setItem: (key: string, value: string) => {
      try {
        localStorage.setItem(key, value);
      } catch (e) {
        console.warn('Storage setItem error:', e);
      }
    },
    removeItem: (key: string) => {
      try {
        localStorage.removeItem(key);
      } catch (e) {
        console.warn('Storage removeItem error:', e);
      }
    },
  };
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

let supabaseClient: ReturnType<typeof createClient<Database>>;

// CRITICAL FIX: Disable auto refresh on login page to prevent network errors
const isLoginPage = typeof window !== 'undefined' && window.location.pathname.includes('/auth/login');

try {
  supabaseClient = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      autoRefreshToken: !isLoginPage, // ✅ Disable on login page
      persistSession: !isLoginPage,    // ✅ Don't persist on login page
      detectSessionInUrl: !isLoginPage, // ✅ Don't detect session on login page
      flowType: 'pkce',
      storage: createSafeStorage(),
      storageKey: `sb-ypwxsmytkvaefmmlkspf-auth-token`,
      debug: false,
    },
    global: {
      headers: {
        'X-Client-Info': 'cateringms-web',
      },
    },
  });
} catch (error) {
  console.error('Fatal error creating Supabase client:', error);
  // Create a minimal fallback client that won't throw errors
  supabaseClient = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      autoRefreshToken: false,
      persistSession: false,
      detectSessionInUrl: false,
    },
  });
}

export const supabase = supabaseClient;
