// This file is automatically generated. Do not edit it directly.
// Types are generated from the Supabase database schema using the Supabase CLI.
 

import type { Database as DB } from './database.types';

export type { Database } from "./database.types";

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Tables<T extends keyof DB["public"]["Tables"]> = DB["public"]["Tables"][T]["Row"];
export type Enums<T extends keyof Database['public']['Enums']> = Database['public']['Enums'][T];
export type Functions<T extends keyof Database['public']['Functions']> = Database['public']['Functions'][T];

// Project reference: ypwxsmytkvaefmmlkspf
// Last updated: 2025-10-16T19:46:52.259607
